totalBuku = 3 * 25000
totalPulpen = 2 * 8000
totalFlashdisk = 1 * 75000
totalBelanja = totalBuku + totalPulpen + totalFlashdisk
diskon = float(totalBelanja * 10) / 100
setelahDiskon = totalBelanja - diskon
ppn = float(setelahDiskon * 11) / 100
totalBayar = setelahDiskon + ppn
uangBayar = 200000
kembalian = uangBayar - totalBayar
print("Total harga buku = Rp" + str(totalBuku))
print("Total Harga pulpen = Rp" + str(totalPulpen))
print("Total harga flashdisk = Rp" + str(totalFlashdisk))
print("Total seluruh barang = Rp" + str(totalBelanja))
print("Diskon 10% = Rp" + str(diskon))
print("Harga setelah diskon = Rp" + str(setelahDiskon))
print("PPN 11% = Rp" + str(ppn))
print("Total pembayarn = Rp" + str(totalBayar))
print("Uang dibayarkan = Rp" + str(uangBayar))
print("Uang kembalian = Rp" + str(kembalian))
